<div class="row">
    <div class="col-md-12 text-center">
        <h1>Liste des participants</h1>
    </div>
</div>
<div class="row mt-20">
    <div class="col-md-12 text-center">
        <div class="btn-group">
            <button type="button" class="btn btn-danger">Action</button>
            <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
                <li><a href="<?= $this->url('participant/participant-form') ?>">Ajouter un utilisateur</a></li>
                <li><a href="<?= $this->url('participant/generate-bib-numbers') ?>">Générer les numéros de dossards</a></li>
            </ul>
        </div>

        <div class="table-responsive mt-20">
            <table class="table">
                <thead>
                    <tr>
                        <th>Dossard</th>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Sexe</th>
                        <th>Évenement</th>
                        <th>Temps</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php if($this->participants){ ?>
                        <?php
                        /** @var \Application\Entity\User $participant */
                        foreach($this->participants as $participant){ ?>
                            <tr>
                                <td><?=$participant->getBibNumber()?></td>
                                <td><?=$participant->getFirstname()?></td>
                                <td><?=$participant->getLastname()?></td>
                                <td><?php
                                        switch($participant->getSex()) {
                                            case "male":
                                                echo "Homme";
                                                break;
                                            case "female":
                                                echo "Femme";
                                                break;
                                        }
                                    ?>
                                </td>
                                <td><?=$participant->getEvent()->getName()?></td>
                                <td><?=$participant->getTime()?></td>
                                <td>
                                    <a class="btn btn-sm btn-default" href="<?= $this->url('participant/participant-change-bib-number', array('id' => $participant->getId())) ?>">Bib number</a>
                                    <a class="btn btn-sm btn-default" href="<?= $this->url('participant/participant-set-time', array('id' => $participant->getId())) ?>">Save time</a>
                                    <a class="btn btn-sm btn-default" href="<?= $this->url('participant/participant-form', array('id' => $participant->getId())) ?>">Edit</a>
                                    <a class="btn btn-sm btn-default" href="<?= $this->url('participant/delete', array('id' => $participant->getId())) ?>">Delete</a>
                                </td>
                            </tr>
                        <?php } ?>
                    <?php } ?>

                </tbody>
            </table>
        </div>
    </div>
</div>
