<div class="row">
    <div class="col-md-12 text-center">
        <h1>Enregistrer un temps</h1>
    </div>
</div>

<div class="row mt-20">
    <div class="col-md-12">
        <?php
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <?=$this->formElement($form->get('id'))?>
        <div class="form-group">
            <label class="col-sm-2 control-label"><?=$this->formLabel($form->get('bibNumber'))?></label>
            <div id="div" class="col-sm-10">
                <?=$this->formElement($form->get('bibNumber'))?>
                <?=$this->formElementErrors($form->get('bibNumber'))?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <?=$this->formSubmit($form->get('submit'));?>
            </div>
        </div>
        <?=$this->form()->closeTag();?>
    </div>
</div>